const renderFeedbackReportPDF = (doc, {
  title,
  generatedBy,
  generatedDate,
  organizationName,
  period,
  summary = {},
  ratingDistribution = [],
  feedbackComments = []
}) => {
  // Header
  doc.rect(0, 0, doc.page.width, 60).fill('#2d3748');
  doc.fillColor('#fff').font('Helvetica-Bold').fontSize(22).text('Organisation Training Management System', 40, 20, { align: 'left' });
  doc.fillColor('#2d3748');
  doc.moveDown(2);

  // Title and meta
  doc.font('Helvetica-Bold').fontSize(18).text(title || 'Feedback Analysis Report', { align: 'center' });
  doc.moveDown(0.5);
  doc.font('Helvetica').fontSize(12).text(`Generated on: ${generatedDate ? new Date(generatedDate).toLocaleDateString() : ''}`);
  doc.font('Helvetica').fontSize(12).text(`Generated by: ${generatedBy || 'OTMS Admin Panel'}`);
  doc.moveDown(0.5);

  // Organization and period
  if (organizationName) doc.font('Helvetica-Bold').fontSize(13).text(`🏢 Organization: ${organizationName}`);
  if (period && period.startDate && period.endDate) doc.font('Helvetica').fontSize(12).text(`📅 Reporting Period: ${period.startDate} – ${period.endDate}`);
  doc.moveDown(1);

  // Summary
  doc.font('Helvetica-Bold').fontSize(14).text('Summary');
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(12).text(`Total Feedback: ${summary.totalFeedback ?? 0}`);
  doc.font('Helvetica').fontSize(12).text(`Average Overall Rating: ${summary.avgOverallRating ? summary.avgOverallRating.toFixed(2) : 'N/A'}`);
  doc.font('Helvetica').fontSize(12).text(`Average Content Rating: ${summary.avgContentRating ? summary.avgContentRating.toFixed(2) : 'N/A'}`);
  doc.font('Helvetica').fontSize(12).text(`Average Instructor Rating: ${summary.avgInstructorRating ? summary.avgInstructorRating.toFixed(2) : 'N/A'}`);
  doc.moveDown(1);

  // Rating Distribution Table
  doc.font('Helvetica-Bold').fontSize(14).text('Rating Distribution');
  doc.moveDown(0.3);
  doc.font('Helvetica-Bold').fontSize(12)
    .text('Rating', 40, doc.y, { width: 100 })
    .text('Count', 150, doc.y, { width: 100 });
  doc.moveDown(0.2);
  ratingDistribution.forEach(row => {
    doc.font('Helvetica').fontSize(11)
      .text(row._id, 40, doc.y, { width: 100 })
      .text(row.count, 150, doc.y, { width: 100 });
    doc.moveDown(0.1);
  });
  doc.moveDown(1);

  // Feedback Comments
  doc.font('Helvetica-Bold').fontSize(14).text('Feedback Comments');
  doc.moveDown(0.3);
  if (Array.isArray(feedbackComments) && feedbackComments.length > 0) {
    feedbackComments.forEach(comment => {
      doc.font('Helvetica-Oblique').fontSize(12).text(`"${comment}"`);
      doc.moveDown(0.2);
    });
  } else {
    doc.font('Helvetica').fontSize(12).text('No feedback comments available.');
  }
  doc.moveDown(2);

  // Footer
  doc.font('Helvetica').fontSize(10).fillColor('#718096')
    .text('Report generated by OTMS – Streamlining inclusive training experiences. For internal use only.', 0, doc.page.height - 40, { align: 'center' });
};

module.exports = { renderFeedbackReportPDF }; 